import { cn } from "@/lib/utils";
import { Link } from "@tanstack/react-router";
import { Info } from "lucide-react";
import type { ButtonHTMLAttributes, ReactNode } from "react";
import {
  Tooltip,
  TooltipContent,
  TooltipProvider,
  TooltipTrigger,
} from "@/components/ui/tooltip";

export function SectionLabel({ children }: { children: ReactNode }) {
  return (
    <span className="section-label">
      <span className="h-1.5 w-1.5 rounded-full bg-[#0052FF]" />
      {children}
    </span>
  );
}

type GBProps = ButtonHTMLAttributes<HTMLButtonElement> & {
  as?: "button";
};

export function GradientButton({ className, children, ...props }: GBProps) {
  return (
    <button
      {...props}
      className={cn(
        "inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-accent px-5 py-3 text-sm font-medium text-white shadow-lg shadow-[#0052FF]/20 transition hover:brightness-110 hover:-translate-y-0.5 active:scale-[0.98] disabled:opacity-60 disabled:pointer-events-none",
        className,
      )}
    >
      {children}
    </button>
  );
}

export function GradientLink({
  to,
  children,
  className,
}: {
  to: string;
  children: ReactNode;
  className?: string;
}) {
  return (
    <Link
      to={to}
      className={cn(
        "inline-flex items-center justify-center gap-2 rounded-xl bg-gradient-accent px-5 py-3 text-sm font-medium text-white shadow-lg shadow-[#0052FF]/20 transition hover:brightness-110 hover:-translate-y-0.5 active:scale-[0.98]",
        className,
      )}
    >
      {children}
    </Link>
  );
}

const AGENT_ROLES: Record<string, string> = {
  "Planner Agent": "Reads your goal and decides how to sequence the whole course.",
  "Curriculum Agent": "Designs modules and learning objectives from your goal.",
  "Content Agent": "Writes the lesson explanations, examples, and analogies.",
  "Assessment Agent": "Builds quizzes and flashcards to check your understanding.",
  "QA Agent": "Reviews everything for accuracy, tone, and coherence.",
  "Tutor Agent": "Answers your questions Socratically while you learn.",
  "Media Agent": "Sources or generates diagrams, images, and visual aids.",
};

export function AgentTag({ agent }: { agent: string }) {
  const desc = AGENT_ROLES[agent] ?? "One of Lurnexa's specialist agents.";
  return (
    <TooltipProvider delayDuration={100}>
      <Tooltip>
        <TooltipTrigger asChild>
          <span className="inline-flex items-center gap-1.5 rounded-full border border-[#0052FF]/20 bg-[#0052FF]/5 px-2 py-0.5 font-mono text-[10px] uppercase tracking-wider text-[#0052FF]">
            <span className="h-1 w-1 rounded-full bg-[#0052FF]" />
            Generated by {agent}
            <Info className="h-3 w-3" />
          </span>
        </TooltipTrigger>
        <TooltipContent className="max-w-xs">{desc}</TooltipContent>
      </Tooltip>
    </TooltipProvider>
  );
}
